<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Semantic mail kinds for the FlexAccess mail queue.
 *
 * The queue stores only the semantic kind and a non-secret payload. Tokens are generated by
 * the worker immediately before sending and are never placed in the queue.
 *
 * @package    auth_flexaccess
 * @copyright  2026 Ralf Erlebach
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace auth_flexaccess\local;

/** Enumerates the semantic FlexAccess mail kinds. */
final class mail_kind {
    /** E-mail confirmation / activation link. */
    public const ACTIVATION = 'activation';
    /** Persistence reminder in the temporary -> authenticated funnel. */
    public const PERSISTENCE_FOLLOWUP = 'persistence_followup';
    /** One-time account deletion link. */
    public const ACCOUNT_DELETE = 'account_delete';

    /**
     * All supported mail kinds.
     *
     * @return array<string>
     */
    public static function values(): array {
        return [self::ACTIVATION, self::PERSISTENCE_FOLLOWUP, self::ACCOUNT_DELETE];
    }
}
