<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Throttled FlexAccess mail worker.
 *
 * Processes due queue entries under the rolling-hour limit. Secret tokens are generated by the
 * token service immediately before sending and are never stored in the queue (ADR-013).
 *
 * @package    auth_flexaccess
 * @copyright  2026 Ralf Erlebach
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace auth_flexaccess\local;

/**
 * Sends queued FlexAccess mails within the configured throttle.
 *
 * @package    auth_flexaccess
 */
final class mail_worker {
    /**
     * Queue table.
     */
    private const TABLE = 'auth_flexaccess_mailqueue';
    /**
     * Max delivery attempts before a job is marked failed.
     */
    private const MAX_ATTEMPTS = 5;
    /**
     * Backoff between attempts, in seconds.
     */
    private const BACKOFF = 900;

    /**
     * Run the worker: compute remaining hourly capacity and process due jobs.
     *
     * @param int|null $now Current time.
     * @return int Number of jobs sent.
     */
    public static function run(?int $now = null): int {
        $now = $now ?? time();
        $factory = \core\lock\lock_config::get_lock_factory('auth_flexaccess_mailqueue');
        $lock = $factory->get_lock('worker', 5);
        if (!$lock) {
            return 0;
        }
        try {
            $limit = (int) get_config('auth_flexaccess', 'maillimitperhour');
            if (!in_array($limit, mail_rate::ALLOWED_LIMITS, true)) {
                $limit = 100;
            }
            $remaining = mail_rate::remaining($limit, self::count_sent_last_hour($now));
            return self::process_due($now, $remaining);
        } finally {
            $lock->release();
        }
    }

    /**
     * Count mails sent in the preceding rolling hour.
     *
     * @param int $now Current time.
     * @return int
     */
    public static function count_sent_last_hour(int $now): int {
        global $DB;
        return (int) $DB->count_records_select(
            self::TABLE,
            "status = :status AND timesent > :since",
            ['status' => 'sent', 'since' => $now - HOURSECS]
        );
    }

    /**
     * Process due jobs up to the remaining capacity.
     *
     * @param int $now Current time.
     * @param int|null $remaining Remaining hourly capacity; null means unlimited.
     * @return int Number of jobs sent.
     */
    public static function process_due(int $now, ?int $remaining): int {
        global $DB;
        $due = $DB->get_records_select(
            self::TABLE,
            "status = :status AND nextrun <= :now",
            ['status' => 'queued', 'now' => $now],
            'nextrun ASC'
        );
        $budget = mail_planner::sendable($remaining, count($due));
        $sent = 0;
        foreach ($due as $job) {
            if ($sent >= $budget) {
                break;
            }
            if (self::deliver($job, $now)) {
                $sent++;
            }
        }
        return $sent;
    }

    /**
     * Deliver a single job, updating its status.
     *
     * @param \stdClass $job Queue row.
     * @param int $now Current time.
     * @return bool Whether the job was sent.
     */
    private static function deliver(\stdClass $job, int $now): bool {
        global $DB;
        try {
            if ($job->mailtype === mail_kind::PERSISTENCE_FOLLOWUP) {
                self::send_persistence_followup($job, $now);
            } else {
                throw new \moodle_exception('error');
            }
            $job->status = 'sent';
            $job->timesent = $now;
            $DB->update_record(self::TABLE, $job);
            return true;
        } catch (\Throwable $e) {
            $job->attempts = (int) $job->attempts + 1;
            if ($job->attempts >= self::MAX_ATTEMPTS) {
                $job->status = 'failed';
            } else {
                $job->nextrun = $now + self::BACKOFF;
            }
            $DB->update_record(self::TABLE, $job);
            return false;
        }
    }

    /**
     * Send a persistence follow-up, issuing the token immediately before sending.
     *
     * @param \stdClass $job Queue row.
     * @param int $now Current time.
     * @return void
     */
    private static function send_persistence_followup(\stdClass $job, int $now): void {
        global $DB;
        $user = $DB->get_record('user', ['id' => $job->userid], '*', MUST_EXIST);
        $token = token_service::issue((int) $job->userid, 'persistence', token_service::DEFAULT_TTL, $now);
        $url = new \moodle_url('/auth/flexaccess/persist.php', ['token' => $token]);
        $subject = get_string('followup:subject', 'auth_flexaccess');
        $body = get_string('followup:body', 'auth_flexaccess', $url->out(false));
        email_to_user($user, self::from_user(), $subject, $body);
    }

    /**
     * Resolve the sender, honouring the optional configured sender address.
     *
     * @return \stdClass
     */
    private static function from_user(): \stdClass {
        $support = \core_user::get_support_user();
        $email = get_config('auth_flexaccess', 'senderemail');
        if (!empty($email) && validate_email($email)) {
            $from = clone $support;
            $from->email = $email;
            return $from;
        }
        return $support;
    }
}
