<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Throttled FlexAccess mail worker.
 *
 * Processes due queue entries under the rolling-hour limit. Secret tokens are generated by the
 * token service immediately before sending and are never stored in the queue (ADR-013).
 *
 * @package    auth_flexaccess
 * @copyright  2026 Ralf Erlebach
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace auth_flexaccess\local;

/**
 * Sends queued FlexAccess mails within the configured throttle.
 *
 * @package    auth_flexaccess
 */
final class mail_worker {
    /**
     * Maximum queue rows fetched per run, so a large backlog cannot exhaust memory.
     */
    private const MAX_BATCH = 200;

    /**
     * Queue table.
     */
    private const TABLE = 'auth_flexaccess_mailqueue';
    /**
     * Max delivery attempts before a job is marked failed.
     */
    private const MAX_ATTEMPTS = 5;
    /**
     * Backoff between attempts, in seconds.
     */
    private const BACKOFF = 900;

    /**
     * Delete delivered (sent) and permanently-failed jobs older than the retention cutoff.
     *
     * Keeps the queue table bounded; live (queued) jobs are never touched.
     *
     * @param int $olderthan Delete finished jobs whose timecreated is below this value.
     * @return void
     */
    public static function prune_delivered(int $olderthan): void {
        global $DB;
        $DB->delete_records_select(
            self::TABLE,
            "status IN ('sent', 'failed') AND timecreated < :cutoff",
            ['cutoff' => $olderthan]
        );
    }

    /**
     * Run the worker: compute remaining hourly capacity and process due jobs.
     *
     * @param int|null $now Current time.
     * @return int Number of jobs sent.
     */
    public static function run(?int $now = null): int {
        $now = $now ?? time();
        $factory = \core\lock\lock_config::get_lock_factory('auth_flexaccess_mailqueue');
        $lock = $factory->get_lock('worker', 5);
        if (!$lock) {
            return 0;
        }
        try {
            $limit = (int) get_config('auth_flexaccess', 'maillimitperhour');
            if (!in_array($limit, mail_rate::ALLOWED_LIMITS, true)) {
                $limit = 100;
            }
            $remaining = mail_rate::remaining($limit, self::count_sent_last_hour($now));
            return self::process_due($now, $remaining);
        } finally {
            $lock->release();
        }
    }

    /**
     * Count mails sent in the preceding rolling hour.
     *
     * @param int $now Current time.
     * @return int
     */
    public static function count_sent_last_hour(int $now): int {
        global $DB;
        return (int) $DB->count_records_select(
            self::TABLE,
            "status = :status AND timesent > :since",
            ['status' => 'sent', 'since' => $now - HOURSECS]
        );
    }

    /**
     * Process due jobs up to the remaining capacity.
     *
     * @param int $now Current time.
     * @param int|null $remaining Remaining hourly capacity; null means unlimited.
     * @return int Number of jobs sent.
     */
    public static function process_due(int $now, ?int $remaining): int {
        global $DB;
        $due = $DB->get_records_select(
            self::TABLE,
            "status = :status AND nextrun <= :now",
            ['status' => 'queued', 'now' => $now],
            'nextrun ASC',
            '*',
            0,
            self::MAX_BATCH
        );
        // Batch-load the sender-side user records once instead of one query per job (avoids N+1).
        $userids = [];
        foreach ($due as $job) {
            if (!empty($job->userid)) {
                $userids[(int) $job->userid] = (int) $job->userid;
            }
        }
        $usermap = $userids ? $DB->get_records_list('user', 'id', $userids) : [];
        $budget = mail_planner::sendable($remaining, count($due));
        $sent = 0;
        foreach ($due as $job) {
            if ($sent >= $budget) {
                break;
            }
            if (self::deliver($job, $now, $usermap)) {
                $sent++;
            }
        }
        return $sent;
    }

    /**
     * Issue a fresh token and render a token job's subject and body at delivery time.
     *
     * The secret is created here, immediately before sending, so it is never persisted in the queue.
     * Any previously issued (undelivered) token for the same purpose is revoked first, so a retry
     * leaves exactly one live secret. The lifetime is re-capped against the account's current
     * remaining validity to preserve SEC-03 even if the job waited in the queue.
     *
     * @param \stdClass $job Queue row.
     * @param array $payload Decoded token payload (kind, purpose, ttl).
     * @param int $now Current time.
     * @return array{0: string, 1: string, 2: string} Subject, plain body, HTML body.
     */
    private static function render_token_job(\stdClass $job, array $payload, int $now): array {
        $userid = (int) $job->userid;
        $purpose = (string) ($payload['purpose'] ?? '');
        $ttl = (int) ($payload['ttl'] ?? 0);
        $page = \auth_flexaccess\local\mail_renderer::page_for_purpose($purpose);
        if ($page === null || $userid === 0 || $ttl <= 0) {
            return ['', '', ''];
        }

        // Re-cap the lifetime against the account's current remaining validity (SEC-03).
        $account = \auth_flexaccess\api::get_account($userid);
        if ($account && $account->timeexpires !== null) {
            $ttl = min($ttl, max(1, (int) $account->timeexpires - $now));
        }

        \auth_flexaccess\local\token_service::revoke_pending($userid, $purpose);
        $token = \auth_flexaccess\local\token_service::issue($userid, $purpose, $ttl, $now);
        $link = (new \moodle_url($page, ['token' => $token]))->out(false);

        return \auth_flexaccess\local\mail_renderer::render((string) $job->mailtype, $link);
    }

    /**
     * Deliver a single job, updating its status.
     *
     * @param \stdClass $job Queue row.
     * @param int $now Current time.
     * @param array $usermap Pre-loaded user records keyed by id (avoids per-job lookups).
     * @return bool Whether the job was sent.
     */
    private static function deliver(\stdClass $job, int $now, array $usermap = []): bool {
        global $DB;
        try {
            $payload = json_decode((string) $job->payloadjson, true);
            if (is_array($payload) && ($payload['kind'] ?? '') === 'token') {
                [$subject, $body, $bodyhtml] = self::render_token_job($job, $payload, $now);
            } else {
                $subject = is_array($payload) ? (string) ($payload['subject'] ?? '') : '';
                $body = is_array($payload) ? (string) ($payload['body'] ?? '') : '';
                $bodyhtml = is_array($payload) ? (string) ($payload['bodyhtml'] ?? '') : '';
            }
            if ($subject === '' || (string) $job->recipient === '') {
                // A malformed or legacy job that this version can no longer deliver; drop it
                // without retrying so it cannot block the queue.
                $job->status = 'failed';
                $DB->update_record(self::TABLE, $job);
                return false;
            }
            $recipient = self::recipient_user($job, $usermap);
            if (!email_to_user($recipient, self::from_user(), $subject, $body, $bodyhtml)) {
                // The mailer returned false: treat as a delivery failure so the job is retried
                // rather than silently marked as sent.
                throw new \moodle_exception('mailsendfailed', 'auth_flexaccess');
            }
            $job->status = 'sent';
            $job->timesent = $now;
            $DB->update_record(self::TABLE, $job);
            return true;
        } catch (\Throwable $e) {
            $job->attempts = (int) $job->attempts + 1;
            if ($job->attempts >= self::MAX_ATTEMPTS) {
                $job->status = 'failed';
            } else {
                $job->nextrun = $now + self::BACKOFF;
            }
            $DB->update_record(self::TABLE, $job);
            return false;
        }
    }

    /**
     * Build the recipient user object for a queued job (a real user, addressed at job->recipient).
     *
     * @param \stdClass $job Queue row.
     * @param array $usermap Pre-loaded user records keyed by id.
     * @return \stdClass
     */
    private static function recipient_user(\stdClass $job, array $usermap = []): \stdClass {
        global $DB;
        $user = null;
        if (!empty($job->userid)) {
            // Prefer the batch-loaded map; fall back to a direct read for out-of-band callers.
            $user = $usermap[(int) $job->userid]
                ?? ($DB->get_record('user', ['id' => $job->userid], '*', IGNORE_MISSING) ?: null);
        }
        if (!$user) {
            $user = \core_user::get_noreply_user();
        }
        $recipient = clone $user;
        $recipient->email = $job->recipient;
        $recipient->emailstop = 0;
        $recipient->mailformat = 1;
        return $recipient;
    }


    /**
     * Resolve the sender, honouring the optional configured sender address.
     *
     * @return \stdClass
     */
    private static function from_user(): \stdClass {
        $support = \core_user::get_support_user();
        $email = get_config('auth_flexaccess', 'senderemail');
        if (!empty($email) && validate_email($email)) {
            $from = clone $support;
            $from->email = $email;
            return $from;
        }
        return $support;
    }
}
